apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: default
spec:
  rules:
  - host: my.example.com
    http:
      paths:
      - backend:
          serviceName: frontend-svc
          servicePort: 80