apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-svc-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /site
        backend:
          serviceName: frontend-svc
          servicePort: port80